import { useCallback, useMemo, memo } from 'react';
import {
  Logo,
  LogoWord,
  LogoNetwork,
  LogoWithWords,
} from './Logo';
import {
  IllusChecked,
  IllusEmailError,
  IllusLinkExpired,
  Illus2FA,
  IllusLocked,
  IllusError,
  IllusRegoinNotSupported,
  IllusIDCard,
  IllusVerification
} from './Illustrations';
import {
  BurgerIcon,
  ReturnIcon,
  CloseIcon,
  ArrowIcon,
  CircleIcon,
  TimesIcon,
  DoubleCheckIcon,
  CheckCircleIcon,
  TimesCircleIcon,
  ContentIcon,
  LockedIcon,
  ExclamationIcon,
  ArrowLinkIcon,
  UnionIcon,
  EyeCloseIcon,
  EyeOnIcon,
} from './Old';
import {
  /* Primary Icons */
  DepositIcon,
  WithdrawalIcon,
  ConversionIcon,
  MintTokenIcon,
  BurnTokenIcon,
  AccountLockedIcon,
  PendingIcon,
  SuccessIcon,
  FailIcon,
  ErrorIcon,
  /* Status Icons */
  StatusSuccessIcon,
  StatusFailIcon,
  /* Menu Icons */
  DashboardIcon,
  DigitalAssetIcon,
  AddressBookIcon,
  LinkedBankAccountsIcon,
  ACHIcon,
  WireIcon,
  AccountIcon,
  ProfileIcon,
  SecurityIcon,
  LogoutIcon,
  PortfolioIcon,
  HomeIcon,
  ConvertIcon,
  WithdrawIcon,
  SendIcon,
  MenuDepositIcon,
  CompanyIcon,
  PartiesIcon,
  TransactionsIcon,
  /* Functional Icons */
  ArrowUpIcon,
  ArrowDownIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  AddIcon,
  MinusIcon,
  CrossIcon,
  MoreIcon,
  DropDownIcon,
  DropDownUpIcon,
  CollapseIcon,
  ExtendIcon,
  SpinnerIcon,
  CheckIcon,
  RemoveIcon,
  /* System Icons */
  InfoIcon,
  NotificationsIcon,
  FavoriteIcon,
  TransferHistoryIcon,
  SupportIcon,
  HelpIcon,
  LanguageIcon,
  ShareIcon,
  ProductsIcon,
  HubIcon,
  SystemSecurityIcon,
  FeesIcon,
  SettingsIcon,
  IDIcon,
  ViewBalanceIcon,
  HideBalanceIcon,
  PrivacyIcon,
  CardIcon,
  CoinIcon,
  WalletIcon,
  EmailIcon,
  RewardsIcon,
  TimeIcon,
  LocationIcon,
  CalendarIcon,
  SecurityCheckIcon,
  DevicesIcon,
  ImagesIcon,
  BankIcon,
  CoinsIcon,
  EarnIcon,
  ScanIcon,
  SearchIcon,
  MaintenanceIcon,
  EditFileIcon,
  DocumentIcon,
  UploadIcon,
  GiftIcon,
  FilterIcon,
  ExpandIcon,
  SystemCollapseIcon,
  RefreshIcon,
  TransferIcon,
  LinkIcon,
  SaveIcon,
  LikeIcon,
  DislikeIcon,
  CopyIcon,
  MobileIcon,
  ChatIcon,
} from './SVGs';
/* import types */
import type { FC } from 'react';
import type { IconsProps, IconWrapperProps } from './interface';
import type { LogoWithWordsCustomProps } from './Logo';
import type { IllustrationsCustomProps } from './Illustrations';

const IconList = {
  illusChecked:IllusChecked,
  illusEmailError:IllusEmailError,
  illusLinkExpired:IllusLinkExpired,
  illus2FA:Illus2FA,
  illusLocked:IllusLocked,
  illusError:IllusError,
  illusRegoinNotSupported:IllusRegoinNotSupported,
  illusIDCard:IllusIDCard,
  illusVerification:IllusVerification,

  /* Logo */
  logo: Logo,
  logoWord: LogoWord,
  logoNetwork: LogoNetwork,
  logoWithWords: LogoWithWords,

  /* Old Icons */
  burger: BurgerIcon,
  return: ReturnIcon,
  close: CloseIcon,
  arrow: ArrowIcon,
  circle: CircleIcon,
  times: TimesIcon,
  doubleCheck: DoubleCheckIcon,
  checkCircle: CheckCircleIcon,
  timesCircle: TimesCircleIcon,
  content: ContentIcon,
  locked: LockedIcon,
  exclamation: ExclamationIcon,
  arrowLink: ArrowLinkIcon,
  union: UnionIcon,
  eyeClose: EyeCloseIcon,
  eyeOn: EyeOnIcon,

  /* Primary Icons */
  deposit: DepositIcon,
  withdrawal: WithdrawalIcon,
  conversion: ConversionIcon,
  mintToken: MintTokenIcon,
  burnToken: BurnTokenIcon,
  accountLocked: AccountLockedIcon,
  pending: PendingIcon,
  success: SuccessIcon,
  fail: FailIcon,
  error: ErrorIcon,

  /* Status Icons */
  statusSuccess: StatusSuccessIcon,
  statusFail: StatusFailIcon,

  /* Menu Icons */
  dashboard: DashboardIcon,
  digitalAsset: DigitalAssetIcon,
  addressBook: AddressBookIcon,
  linkedBankAccounts: LinkedBankAccountsIcon,
  ach: ACHIcon,
  wire: WireIcon,
  account: AccountIcon,
  profile: ProfileIcon,
  security: SecurityIcon,
  logout: LogoutIcon,
  portfolio: PortfolioIcon,
  home: HomeIcon,
  convert: ConvertIcon,
  withdraw: WithdrawIcon,
  send: SendIcon,
  menuDeposit: MenuDepositIcon,
  company: CompanyIcon,
  parties: PartiesIcon,
  transactions: TransactionsIcon,

  /* Functional Icons */
  arrowUp: ArrowUpIcon,
  arrowDown: ArrowDownIcon,
  arrowLeft: ArrowLeftIcon,
  arrowRight: ArrowRightIcon,
  add: AddIcon,
  minus: MinusIcon,
  cross: CrossIcon,
  more: MoreIcon,
  dropDown: DropDownIcon,
  dropDownUp: DropDownUpIcon,
  collapse: CollapseIcon,
  extend: ExtendIcon,
  spinner: SpinnerIcon,
  check: CheckIcon,
  remove: RemoveIcon,

  /* System Icons */
  info: InfoIcon,
  notifications: NotificationsIcon,
  favorite: FavoriteIcon,
  transferHistory: TransferHistoryIcon,
  support: SupportIcon,
  help: HelpIcon,
  language: LanguageIcon,
  share: ShareIcon,
  products: ProductsIcon,
  hub: HubIcon,
  systemSecurity: SystemSecurityIcon,
  fees: FeesIcon,
  settings: SettingsIcon,
  id: IDIcon,
  viewBalance: ViewBalanceIcon,
  hideBalance: HideBalanceIcon,
  privacy: PrivacyIcon,
  card: CardIcon,
  coin: CoinIcon,
  wallet: WalletIcon,
  email: EmailIcon,
  rewards: RewardsIcon,
  time: TimeIcon,
  location: LocationIcon,
  calendar: CalendarIcon,
  securityCheck: SecurityCheckIcon,
  devices: DevicesIcon,
  images: ImagesIcon,
  bank: BankIcon,
  coins: CoinsIcon,
  earn: EarnIcon,
  scan: ScanIcon,
  search: SearchIcon,
  maintenance: MaintenanceIcon,
  editFile: EditFileIcon,
  document: DocumentIcon,
  upload: UploadIcon,
  gift: GiftIcon,
  filter: FilterIcon,
  expand: ExpandIcon,
  systemCollapse: SystemCollapseIcon,
  refresh: RefreshIcon,
  transfer: TransferIcon,
  link: LinkIcon,
  save: SaveIcon,
  like: LikeIcon,
  dislike: DislikeIcon,
  copy: CopyIcon,
  mobile: MobileIcon,
  chat: ChatIcon,
} as const;

export type IconName = keyof typeof IconList;

export interface LogoWithWordsProps extends IconsProps, LogoWithWordsCustomProps {
  name: 'logoWithWords';
}

export interface IllustrationsProps extends IconsProps, IllustrationsCustomProps {
  name: 'illusLocked' | 'illusChecked' | 'illusError' | 'illusEmailError' | 'illusLinkExpired' | 'illus2FA' | 'illusIDCard' | 'illusVerification' | 'illusRegoinNotSupported';
}

export const Icons: FC<(IconsProps & { name: IconName }) | LogoWithWordsProps | IllustrationsProps> = ({ name, ...rest }) => {
  const IconComponent = useCallback((props: IconWrapperProps) => {
    const Icon = useMemo(() => IconList[name], [name]);
    return Icon ? <Icon {...props} /> : null;
  }, [name]);

  return <IconComponent {...rest} />;
};

export default memo(Icons);
